language: generic

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

script:
  - bash <(curl -s https://codecov.io/bash) script.sh
